/* automatically generated by rust-bindgen 0.66.1 */

extern "C" {
    pub fn TextToPhonemes(input: *mut ::std::os::raw::c_uchar) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn SetInput(_input: *mut ::std::os::raw::c_char);
}
extern "C" {
    pub fn SetSpeed(_speed: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn SetPitch(_pitch: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn SetMouth(_mouth: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn SetThroat(_throat: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn EnableSingmode();
}
extern "C" {
    pub fn EnableDebug();
}
extern "C" {
    pub fn SAMMain() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn GetBuffer() -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn GetBufferLength() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn PrintPhonemes(
        phonemeindex: *mut ::std::os::raw::c_uchar,
        phonemeLength: *mut ::std::os::raw::c_uchar,
        stress: *mut ::std::os::raw::c_uchar,
    );
}
extern "C" {
    pub fn PrintOutput(
        flag: *mut ::std::os::raw::c_uchar,
        f1: *mut ::std::os::raw::c_uchar,
        f2: *mut ::std::os::raw::c_uchar,
        f3: *mut ::std::os::raw::c_uchar,
        a1: *mut ::std::os::raw::c_uchar,
        a2: *mut ::std::os::raw::c_uchar,
        a3: *mut ::std::os::raw::c_uchar,
        p: *mut ::std::os::raw::c_uchar,
    );
}
extern "C" {
    pub fn PrintRule(offset: ::std::os::raw::c_int);
}
