[package]
name = "rust"
version = "0.1.0"
edition = "2021"
crate-type = ["rlib","cdylib","bin"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.66.1"
cc = "1.0.83"
